### ISSUE TITLE
[Feature Request] Clearification on the arguments in `localOutliers`

### ISSUE THREAD

**Issue by boyiguo1** [MicTott/SpotSweeper#7]
Can you clarify the following points in the documentation?

* Difference between `minPts` vs `n_neighbors`: if I used the default setting of `minPts=20` with `n_neighbors=18` and `method="multivariate"`, what would happen? Does that mean LOF calculation would not be disabled?
* Does `localOutliers` work for multiple samples stored in the same `spe` object? I saw there's an argument called `sample`, does it implies, `localOutlier` will operate one sample by one sample when `length(unique(spe$sample_id))>1`
* Clarify why the default `cutoff` value is 2.58, e.g. 99.5 percentile of a standard normal distribution. Also clarify would this be one-sided (LOF > 2.58) or two sided (|LOF| > 2.58)
* It would be helpful to add what variables added to the updated `colData(spe)`, for example, `LOF`,`local_outliers`, `*_z` and `*_log2` and `coords`.

**Comment by MicTott** [comment]
Hey @boyiguo1 , thanks for feedback. I agree these variables could be made clearer and I'll make a point to do this soon. 

For now:

-  `n_neighbors` is used to define the local neighborhood for local mean/z-score calculation. Once the local z-score values are obtained, `minPts` is used to define the number of points (i.e., neighbors) that is used for LOF calculation within the local z-transformed feature space. LOF calculation is only used if `method="multivariate"`, and thus the `minPts` argument would not be used. 
- Yes, `localOutliers` works with multiple samples. Just provide a string for the column data containing the sample ids to `samples` And yes, `localOutlier` performs the calculations on a per-sample basis. 
- The default z-score `cutoff` of 2.58 corresponds to the 99th percentitle (i.e., p > 0.01) because it was found to work well in initial testing. This is currently two sided.


I'll also make a note to detail some  of these in the improved vignette.
